# Generated by Django 6.0.8 on 2026-08-04 17:57

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printorder',
            name='file_deleted',
            field=models.BooleanField(default=False, help_text='True if file was deleted after 7 days'),
        ),
        migrations.AlterField(
            model_name='printorder',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=orders.models.document_upload_path),
        ),
    ]
