# Generated by Django 6.0.8 on 2026-08-05 11:01

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_printorder_file_deleted_alter_printorder_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='printorder',
            name='page_selection',
            field=models.CharField(blank=True, default='', help_text="Page range string entered by the user, e.g. '5-19' or '1,3,5-10'.", max_length=255),
        ),
        migrations.AddField(
            model_name='printorder',
            name='print_mode',
            field=models.CharField(choices=[('all', 'Print All Pages'), ('specific', 'Print Specific Pages')], default='all', help_text="'all' = every page; 'specific' = user-defined range.", max_length=10),
        ),
        migrations.AddField(
            model_name='printorder',
            name='printable_page_count',
            field=models.PositiveIntegerField(default=1, help_text='Pages actually printed; drives cost calculation.'),
        ),
        migrations.AddField(
            model_name='printorder',
            name='processed_pdf',
            field=models.FileField(blank=True, help_text='Auto-generated PDF containing only the selected pages.', null=True, upload_to=orders.models.processed_upload_path),
        ),
    ]
